/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../types/contracts";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface IBlockRewardHbbftCoins extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IBlockRewardHbbftCoins;
  clone(): IBlockRewardHbbftCoins;
  methods: {
    getDelegatorReward(
      arg0: number | string | BN,
      arg1: number | string | BN,
      arg2: string
    ): NonPayableTransactionObject<string>;

    getValidatorReward(
      arg0: number | string | BN,
      arg1: string
    ): NonPayableTransactionObject<string>;

    transferReward(
      arg0: number | string | BN,
      arg1: string
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
