/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../types/contracts";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface IRandomHbbft extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IRandomHbbft;
  clone(): IRandomHbbft;
  methods: {
    currentSeed(): NonPayableTransactionObject<string>;

    getSeedHistoric(
      _blocknumber: number | string | BN
    ): NonPayableTransactionObject<string>;

    getSeedsHistoric(
      arg0: (number | string | BN)[]
    ): NonPayableTransactionObject<string[]>;

    initialize(arg0: string): NonPayableTransactionObject<void>;

    isFullHealth(): NonPayableTransactionObject<boolean>;

    isFullHealthHistoric(
      arg0: (number | string | BN)[]
    ): NonPayableTransactionObject<boolean[]>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
