/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type CoinsRewarded = ContractEventLog<{
  rewards: string;
  0: string;
}>;
export type EarlyEpochEndNotificationReceived = ContractEventLog<{}>;
export type Initialized = ContractEventLog<{
  version: string;
  0: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type RemoveChangeableParameter = ContractEventLog<{
  funcSelector: string;
  0: string;
}>;
export type SetChangeableParameter = ContractEventLog<{
  setter: string;
  getter: string;
  params: string[];
  0: string;
  1: string;
  2: string[];
}>;
export type SetGovernancePotShareNominator = ContractEventLog<{
  value: string;
  0: string;
}>;

export interface BlockRewardHbbftMock extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): BlockRewardHbbftMock;
  clone(): BlockRewardHbbftMock;
  methods: {
    VALIDATOR_FIXED_REWARD_PERCENT(): NonPayableTransactionObject<string>;

    addToDeltaPot(): PayableTransactionObject<void>;

    addToReinsertPot(): PayableTransactionObject<void>;

    connectivityTracker(): NonPayableTransactionObject<string>;

    deltaPot(): NonPayableTransactionObject<string>;

    deltaPotPayoutFraction(): NonPayableTransactionObject<string>;

    earlyEpochEnd(): NonPayableTransactionObject<boolean>;

    epochPercentage(): NonPayableTransactionObject<string>;

    epochPoolNativeReward(
      arg0: number | string | BN,
      arg1: string
    ): NonPayableTransactionObject<string>;

    epochsPoolGotRewardFor(
      _miningAddress: string
    ): NonPayableTransactionObject<string[]>;

    getAllowedParamsRange(
      _selector: string
    ): NonPayableTransactionObject<[string, string[]]>;

    getAllowedParamsRangeWithSelector(
      _selector: string | number[]
    ): NonPayableTransactionObject<[string, string[]]>;

    getGovernanceAddress(): NonPayableTransactionObject<string>;

    getPotsShares(
      numValidators: number | string | BN
    ): NonPayableTransactionObject<[string, string, string, string]>;

    governancePotAddress(): NonPayableTransactionObject<string>;

    governancePotShareDenominator(): NonPayableTransactionObject<string>;

    governancePotShareNominator(): NonPayableTransactionObject<string>;

    initialize(
      _contractOwner: string,
      _validatorSet: string,
      _connectivityTracker: string
    ): NonPayableTransactionObject<void>;

    isWithinAllowedRange(
      funcSelector: string | number[],
      newVal: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    nativeRewardUndistributed(): NonPayableTransactionObject<string>;

    notifyEarlyEpochEnd(): NonPayableTransactionObject<void>;

    owner(): NonPayableTransactionObject<string>;

    reinsertPot(): NonPayableTransactionObject<string>;

    reinsertPotPayoutFraction(): NonPayableTransactionObject<string>;

    removeAllowedChangeableParameter(
      funcSelector: string | number[]
    ): NonPayableTransactionObject<void>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    resetEarlyEpochEnd(): NonPayableTransactionObject<void>;

    reward(_isEpochEndBlock: boolean): NonPayableTransactionObject<string>;

    sendCoins(): PayableTransactionObject<void>;

    setAllowedChangeableParameter(
      setter: string | number[],
      getter: string | number[],
      params: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    setConnectivityTracker(
      _connectivityTracker: string
    ): NonPayableTransactionObject<void>;

    setGovernanceAddress(_address: string): NonPayableTransactionObject<void>;

    setGovernancePotShareNominator(
      _shareNominator: number | string | BN
    ): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    validatorMinRewardPercent(
      arg0: number | string | BN
    ): NonPayableTransactionObject<string>;

    validatorSetContract(): NonPayableTransactionObject<string>;
  };
  events: {
    CoinsRewarded(cb?: Callback<CoinsRewarded>): EventEmitter;
    CoinsRewarded(
      options?: EventOptions,
      cb?: Callback<CoinsRewarded>
    ): EventEmitter;

    EarlyEpochEndNotificationReceived(
      cb?: Callback<EarlyEpochEndNotificationReceived>
    ): EventEmitter;
    EarlyEpochEndNotificationReceived(
      options?: EventOptions,
      cb?: Callback<EarlyEpochEndNotificationReceived>
    ): EventEmitter;

    Initialized(cb?: Callback<Initialized>): EventEmitter;
    Initialized(
      options?: EventOptions,
      cb?: Callback<Initialized>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    RemoveChangeableParameter(
      cb?: Callback<RemoveChangeableParameter>
    ): EventEmitter;
    RemoveChangeableParameter(
      options?: EventOptions,
      cb?: Callback<RemoveChangeableParameter>
    ): EventEmitter;

    SetChangeableParameter(cb?: Callback<SetChangeableParameter>): EventEmitter;
    SetChangeableParameter(
      options?: EventOptions,
      cb?: Callback<SetChangeableParameter>
    ): EventEmitter;

    SetGovernancePotShareNominator(
      cb?: Callback<SetGovernancePotShareNominator>
    ): EventEmitter;
    SetGovernancePotShareNominator(
      options?: EventOptions,
      cb?: Callback<SetGovernancePotShareNominator>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "CoinsRewarded", cb: Callback<CoinsRewarded>): void;
  once(
    event: "CoinsRewarded",
    options: EventOptions,
    cb: Callback<CoinsRewarded>
  ): void;

  once(
    event: "EarlyEpochEndNotificationReceived",
    cb: Callback<EarlyEpochEndNotificationReceived>
  ): void;
  once(
    event: "EarlyEpochEndNotificationReceived",
    options: EventOptions,
    cb: Callback<EarlyEpochEndNotificationReceived>
  ): void;

  once(event: "Initialized", cb: Callback<Initialized>): void;
  once(
    event: "Initialized",
    options: EventOptions,
    cb: Callback<Initialized>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(
    event: "RemoveChangeableParameter",
    cb: Callback<RemoveChangeableParameter>
  ): void;
  once(
    event: "RemoveChangeableParameter",
    options: EventOptions,
    cb: Callback<RemoveChangeableParameter>
  ): void;

  once(
    event: "SetChangeableParameter",
    cb: Callback<SetChangeableParameter>
  ): void;
  once(
    event: "SetChangeableParameter",
    options: EventOptions,
    cb: Callback<SetChangeableParameter>
  ): void;

  once(
    event: "SetGovernancePotShareNominator",
    cb: Callback<SetGovernancePotShareNominator>
  ): void;
  once(
    event: "SetGovernancePotShareNominator",
    options: EventOptions,
    cb: Callback<SetGovernancePotShareNominator>
  ): void;
}
