/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type CoinsRewarded = ContractEventLog<{
  rewards: string;
  0: string;
}>;
export type Initialized = ContractEventLog<{
  version: string;
  0: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type RemoveChangeAbleParameter = ContractEventLog<{
  funcSelector: string;
  0: string;
}>;
export type SetChangeAbleParameter = ContractEventLog<{
  setter: string;
  getter: string;
  params: string[];
  0: string;
  1: string;
  2: string[];
}>;
export type SetConnectivityTracker = ContractEventLog<{
  _connectivityTracker: string;
  0: string;
}>;
export type SetDeltaPotPayoutFraction = ContractEventLog<{
  _fraction: string;
  0: string;
}>;
export type SetReinsertPotPayoutFraction = ContractEventLog<{
  _fraction: string;
  0: string;
}>;

export interface BlockRewardHbbft extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): BlockRewardHbbft;
  clone(): BlockRewardHbbft;
  methods: {
    REWARD_PERCENT_MULTIPLIER(): NonPayableTransactionObject<string>;

    VALIDATOR_MIN_REWARD_PERCENT(): NonPayableTransactionObject<string>;

    addToDeltaPot(): PayableTransactionObject<void>;

    addToReinsertPot(): PayableTransactionObject<void>;

    allowedParameterRange(
      arg0: string | number[]
    ): NonPayableTransactionObject<string>;

    connectivityTracker(): NonPayableTransactionObject<string>;

    deltaPot(): NonPayableTransactionObject<string>;

    deltaPotPayoutFraction(): NonPayableTransactionObject<string>;

    earlyEpochEnd(): NonPayableTransactionObject<boolean>;

    epochPercentage(): NonPayableTransactionObject<string>;

    epochPoolNativeReward(
      arg0: number | string | BN,
      arg1: string
    ): NonPayableTransactionObject<string>;

    epochsPoolGotRewardFor(
      _miningAddress: string
    ): NonPayableTransactionObject<string[]>;

    getAllowedParamsRange(
      _selector: string
    ): NonPayableTransactionObject<[string, string[]]>;

    getGovernanceAddress(): NonPayableTransactionObject<string>;

    governancePotAddress(): NonPayableTransactionObject<string>;

    governancePotShareDenominator(): NonPayableTransactionObject<string>;

    governancePotShareNominator(): NonPayableTransactionObject<string>;

    initAllowedChangeableParameter(
      setter: string,
      getter: string,
      params: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    initialize(
      _contractOwner: string,
      _validatorSet: string,
      _connectivityTracker: string
    ): NonPayableTransactionObject<void>;

    isWithinAllowedRange(
      funcSelector: string | number[],
      newVal: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    nativeRewardUndistributed(): NonPayableTransactionObject<string>;

    notifyEarlyEpochEnd(): NonPayableTransactionObject<void>;

    owner(): NonPayableTransactionObject<string>;

    reinsertPot(): NonPayableTransactionObject<string>;

    reinsertPotPayoutFraction(): NonPayableTransactionObject<string>;

    removeAllowedChangeableParameter(
      funcSelector: string
    ): NonPayableTransactionObject<void>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    reward(_isEpochEndBlock: boolean): NonPayableTransactionObject<string>;

    setAllowedChangeableParameter(
      setter: string,
      getter: string,
      params: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    setConnectivityTracker(
      _connectivityTracker: string
    ): NonPayableTransactionObject<void>;

    setGovernancePotShareNominator(
      _shareNominator: number | string | BN
    ): NonPayableTransactionObject<void>;

    setReinsertPotPayoutFraction(
      _value: number | string | BN
    ): NonPayableTransactionObject<void>;

    setdeltaPotPayoutFraction(
      _value: number | string | BN
    ): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    validatorMinRewardPercent(
      arg0: number | string | BN
    ): NonPayableTransactionObject<string>;

    validatorSetContract(): NonPayableTransactionObject<string>;
  };
  events: {
    CoinsRewarded(cb?: Callback<CoinsRewarded>): EventEmitter;
    CoinsRewarded(
      options?: EventOptions,
      cb?: Callback<CoinsRewarded>
    ): EventEmitter;

    Initialized(cb?: Callback<Initialized>): EventEmitter;
    Initialized(
      options?: EventOptions,
      cb?: Callback<Initialized>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    RemoveChangeAbleParameter(
      cb?: Callback<RemoveChangeAbleParameter>
    ): EventEmitter;
    RemoveChangeAbleParameter(
      options?: EventOptions,
      cb?: Callback<RemoveChangeAbleParameter>
    ): EventEmitter;

    SetChangeAbleParameter(cb?: Callback<SetChangeAbleParameter>): EventEmitter;
    SetChangeAbleParameter(
      options?: EventOptions,
      cb?: Callback<SetChangeAbleParameter>
    ): EventEmitter;

    SetConnectivityTracker(cb?: Callback<SetConnectivityTracker>): EventEmitter;
    SetConnectivityTracker(
      options?: EventOptions,
      cb?: Callback<SetConnectivityTracker>
    ): EventEmitter;

    SetDeltaPotPayoutFraction(
      cb?: Callback<SetDeltaPotPayoutFraction>
    ): EventEmitter;
    SetDeltaPotPayoutFraction(
      options?: EventOptions,
      cb?: Callback<SetDeltaPotPayoutFraction>
    ): EventEmitter;

    SetReinsertPotPayoutFraction(
      cb?: Callback<SetReinsertPotPayoutFraction>
    ): EventEmitter;
    SetReinsertPotPayoutFraction(
      options?: EventOptions,
      cb?: Callback<SetReinsertPotPayoutFraction>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "CoinsRewarded", cb: Callback<CoinsRewarded>): void;
  once(
    event: "CoinsRewarded",
    options: EventOptions,
    cb: Callback<CoinsRewarded>
  ): void;

  once(event: "Initialized", cb: Callback<Initialized>): void;
  once(
    event: "Initialized",
    options: EventOptions,
    cb: Callback<Initialized>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(
    event: "RemoveChangeAbleParameter",
    cb: Callback<RemoveChangeAbleParameter>
  ): void;
  once(
    event: "RemoveChangeAbleParameter",
    options: EventOptions,
    cb: Callback<RemoveChangeAbleParameter>
  ): void;

  once(
    event: "SetChangeAbleParameter",
    cb: Callback<SetChangeAbleParameter>
  ): void;
  once(
    event: "SetChangeAbleParameter",
    options: EventOptions,
    cb: Callback<SetChangeAbleParameter>
  ): void;

  once(
    event: "SetConnectivityTracker",
    cb: Callback<SetConnectivityTracker>
  ): void;
  once(
    event: "SetConnectivityTracker",
    options: EventOptions,
    cb: Callback<SetConnectivityTracker>
  ): void;

  once(
    event: "SetDeltaPotPayoutFraction",
    cb: Callback<SetDeltaPotPayoutFraction>
  ): void;
  once(
    event: "SetDeltaPotPayoutFraction",
    options: EventOptions,
    cb: Callback<SetDeltaPotPayoutFraction>
  ): void;

  once(
    event: "SetReinsertPotPayoutFraction",
    cb: Callback<SetReinsertPotPayoutFraction>
  ): void;
  once(
    event: "SetReinsertPotPayoutFraction",
    options: EventOptions,
    cb: Callback<SetReinsertPotPayoutFraction>
  ): void;
}
