/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface BonusScoreSystemMock extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): BonusScoreSystemMock;
  clone(): BonusScoreSystemMock;
  methods: {
    DEFAULT_BAD_PERF_FACTOR(): NonPayableTransactionObject<string>;

    DEFAULT_NO_KEY_WRITE_FACTOR(): NonPayableTransactionObject<string>;

    DEFAULT_NO_STAND_BY_FACTOR(): NonPayableTransactionObject<string>;

    DEFAULT_STAND_BY_FACTOR(): NonPayableTransactionObject<string>;

    MAX_SCORE(): NonPayableTransactionObject<string>;

    MIN_SCORE(): NonPayableTransactionObject<string>;

    getValidatorScore(mining: string): NonPayableTransactionObject<string>;

    penaliseBadPerformance(
      mining: string,
      arg1: number | string | BN
    ): NonPayableTransactionObject<void>;

    penaliseNoKeyWrite(mining: string): NonPayableTransactionObject<void>;

    penaliseNoStandBy(
      mining: string,
      arg1: number | string | BN
    ): NonPayableTransactionObject<void>;

    rewardStandBy(
      mining: string,
      arg1: number | string | BN
    ): NonPayableTransactionObject<void>;

    setValidatorScore(
      mining: string,
      value: number | string | BN
    ): NonPayableTransactionObject<void>;

    validatorScore(arg0: string): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
