/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Confirmed = ContractEventLog<{
  who: string;
  0: string;
}>;
export type Initialized = ContractEventLog<{
  version: string;
  0: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type Revoked = ContractEventLog<{
  who: string;
  0: string;
}>;

export interface CertifierHbbft extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): CertifierHbbft;
  clone(): CertifierHbbft;
  methods: {
    certified(_who: string): NonPayableTransactionObject<boolean>;

    certifiedExplicitly(_who: string): NonPayableTransactionObject<boolean>;

    certify(_who: string): NonPayableTransactionObject<void>;

    initialize(
      _certifiedAddresses: string[],
      _validatorSet: string,
      _owner: string
    ): NonPayableTransactionObject<void>;

    owner(): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    revoke(_who: string): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    validatorSetContract(): NonPayableTransactionObject<string>;
  };
  events: {
    Confirmed(cb?: Callback<Confirmed>): EventEmitter;
    Confirmed(options?: EventOptions, cb?: Callback<Confirmed>): EventEmitter;

    Initialized(cb?: Callback<Initialized>): EventEmitter;
    Initialized(
      options?: EventOptions,
      cb?: Callback<Initialized>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    Revoked(cb?: Callback<Revoked>): EventEmitter;
    Revoked(options?: EventOptions, cb?: Callback<Revoked>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Confirmed", cb: Callback<Confirmed>): void;
  once(
    event: "Confirmed",
    options: EventOptions,
    cb: Callback<Confirmed>
  ): void;

  once(event: "Initialized", cb: Callback<Initialized>): void;
  once(
    event: "Initialized",
    options: EventOptions,
    cb: Callback<Initialized>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(event: "Revoked", cb: Callback<Revoked>): void;
  once(event: "Revoked", options: EventOptions, cb: Callback<Revoked>): void;
}
