/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ConnectivityTrackerHbbftMock extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ConnectivityTrackerHbbftMock;
  clone(): ConnectivityTrackerHbbftMock;
  methods: {
    earlyEpochEnd(
      arg0: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    isEarlyEpochEnd(
      epoch: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    setEarlyEpochEnd(
      epoch: number | string | BN,
      set: boolean
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
