/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type ChangeVote = ContractEventLog<{
  voter: string;
  proposalId: string;
  vote: string;
  reason: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type Initialized = ContractEventLog<{
  version: string;
  0: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type ProposalCanceled = ContractEventLog<{
  proposer: string;
  proposalId: string;
  reason: string;
  0: string;
  1: string;
  2: string;
}>;
export type ProposalCreated = ContractEventLog<{
  proposer: string;
  proposalId: string;
  targets: string[];
  values: string[];
  calldatas: string[];
  title: string;
  description: string;
  discussionUrl: string;
  proposalFee: string;
  0: string;
  1: string;
  2: string[];
  3: string[];
  4: string[];
  5: string;
  6: string;
  7: string;
  8: string;
}>;
export type ProposalExecuted = ContractEventLog<{
  caller: string;
  proposalId: string;
  0: string;
  1: string;
}>;
export type RemoveChangeableParameter = ContractEventLog<{
  funcSelector: string;
  0: string;
}>;
export type SetChangeAbleParameters = ContractEventLog<{
  allowed: boolean;
  setter: string;
  getter: string;
  params: string[];
  0: boolean;
  1: string;
  2: string;
  3: string[];
}>;
export type SetChangeableParameter = ContractEventLog<{
  setter: string;
  getter: string;
  params: string[];
  0: string;
  1: string;
  2: string[];
}>;
export type SetCreateProposalFee = ContractEventLog<{
  fee: string;
  0: string;
}>;
export type SetIsCoreContract = ContractEventLog<{
  contractAddress: string;
  isCore: boolean;
  0: string;
  1: boolean;
}>;
export type SubmitVote = ContractEventLog<{
  voter: string;
  proposalId: string;
  vote: string;
  0: string;
  1: string;
  2: string;
}>;
export type SubmitVoteWithReason = ContractEventLog<{
  voter: string;
  proposalId: string;
  vote: string;
  reason: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type SwitchDaoPhase = ContractEventLog<{
  phase: string;
  start: string;
  end: string;
  0: string;
  1: string;
  2: string;
}>;
export type VotingFinalized = ContractEventLog<{
  caller: string;
  proposalId: string;
  accepted: boolean;
  0: string;
  1: string;
  2: boolean;
}>;

export interface DiamondDao extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): DiamondDao;
  clone(): DiamondDao;
  methods: {
    DAO_PHASE_DURATION(): NonPayableTransactionObject<string>;

    MAX_NEW_PROPOSALS(): NonPayableTransactionObject<string>;

    cancel(
      proposalId: number | string | BN,
      reason: string
    ): NonPayableTransactionObject<void>;

    changeVote(
      proposalId: number | string | BN,
      _vote: number | string | BN,
      reason: string
    ): NonPayableTransactionObject<void>;

    countVotes(
      proposalId: number | string | BN
    ): NonPayableTransactionObject<[string, string, string, string]>;

    createProposalFee(): NonPayableTransactionObject<string>;

    currentPhaseProposals(
      arg0: number | string | BN
    ): NonPayableTransactionObject<string>;

    daoEpochStakeSnapshot(
      arg0: number | string | BN,
      arg1: string
    ): NonPayableTransactionObject<string>;

    daoEpochTotalStakeSnapshot(
      arg0: number | string | BN
    ): NonPayableTransactionObject<string>;

    daoPhase(): NonPayableTransactionObject<{
      start: string;
      end: string;
      daoEpoch: string;
      phase: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    daoPhaseCount(): NonPayableTransactionObject<string>;

    daoPhaseProposals(
      arg0: number | string | BN,
      arg1: number | string | BN
    ): NonPayableTransactionObject<string>;

    execute(
      proposalId: number | string | BN
    ): NonPayableTransactionObject<void>;

    finalize(
      proposalId: number | string | BN
    ): NonPayableTransactionObject<void>;

    getAllowedParamsRange(
      _selector: string
    ): NonPayableTransactionObject<[string, string[]]>;

    getAllowedParamsRangeWithSelector(
      _selector: string | number[]
    ): NonPayableTransactionObject<[string, string[]]>;

    getCurrentPhaseProposals(): NonPayableTransactionObject<string[]>;

    getProposal(
      proposalId: number | string | BN
    ): NonPayableTransactionObject<
      [
        string,
        string,
        string,
        string[],
        string[],
        string[],
        string,
        string,
        string,
        string,
        string,
        string
      ]
    >;

    getProposalVoters(
      proposalId: number | string | BN
    ): NonPayableTransactionObject<string[]>;

    getProposalVotersCount(
      proposalId: number | string | BN
    ): NonPayableTransactionObject<string>;

    governancePot(): NonPayableTransactionObject<string>;

    hashProposal(
      targets: string[],
      values: (number | string | BN)[],
      calldatas: (string | number[])[],
      description: string
    ): NonPayableTransactionObject<string>;

    initialize(
      _contractOwner: string,
      _validatorSet: string,
      _stakingHbbft: string,
      _reinsertPot: string,
      _txPermission: string,
      _lowMajorityDao: string,
      _createProposalFee: number | string | BN,
      _startTimestamp: number | string | BN
    ): NonPayableTransactionObject<void>;

    initializeV2(_lowMajorityDao: string): NonPayableTransactionObject<void>;

    isCoreContract(arg0: string): NonPayableTransactionObject<boolean>;

    isWithinAllowedRange(
      funcSelector: string | number[],
      newVal: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    lastDaoPhaseCount(): NonPayableTransactionObject<string>;

    lowMajorityDao(): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    proposalExists(
      proposalId: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    proposals(arg0: number | string | BN): NonPayableTransactionObject<{
      proposer: string;
      votingDaoEpoch: string;
      state: string;
      title: string;
      description: string;
      discussionUrl: string;
      daoPhaseCount: string;
      proposalFee: string;
      proposalType: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: string;
      7: string;
      8: string;
    }>;

    propose(
      targets: string[],
      values: (number | string | BN)[],
      calldatas: (string | number[])[],
      title: string,
      description: string,
      discussionUrl: string,
      majority: number | string | BN
    ): PayableTransactionObject<void>;

    quorumReached(
      proposalId: number | string | BN,
      _type: number | string | BN,
      result: [
        number | string | BN,
        number | string | BN,
        number | string | BN,
        number | string | BN
      ]
    ): NonPayableTransactionObject<boolean>;

    reinsertPot(): NonPayableTransactionObject<string>;

    removeAllowedChangeableParameter(
      funcSelector: string | number[]
    ): NonPayableTransactionObject<void>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    results(arg0: number | string | BN): NonPayableTransactionObject<{
      countYes: string;
      countNo: string;
      stakeYes: string;
      stakeNo: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    setAllowedChangeableParameter(
      setter: string | number[],
      getter: string | number[],
      params: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    setCreateProposalFee(
      _fee: number | string | BN
    ): NonPayableTransactionObject<void>;

    setIsCoreContract(
      _add: string,
      isCore: boolean
    ): NonPayableTransactionObject<void>;

    stakingHbbft(): NonPayableTransactionObject<string>;

    statistic(): NonPayableTransactionObject<{
      total: string;
      accepted: string;
      declined: string;
      canceled: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    switchPhase(): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    unfinalizedProposals(): NonPayableTransactionObject<string>;

    unfinalizedProposalsExist(): NonPayableTransactionObject<boolean>;

    validatorSet(): NonPayableTransactionObject<string>;

    vote(
      proposalId: number | string | BN,
      _vote: number | string | BN
    ): NonPayableTransactionObject<void>;

    voteWithReason(
      proposalId: number | string | BN,
      _vote: number | string | BN,
      reason: string
    ): NonPayableTransactionObject<void>;

    votes(
      arg0: number | string | BN,
      arg1: string
    ): NonPayableTransactionObject<{
      timestamp: string;
      vote: string;
      reason: string;
      0: string;
      1: string;
      2: string;
    }>;
  };
  events: {
    ChangeVote(cb?: Callback<ChangeVote>): EventEmitter;
    ChangeVote(options?: EventOptions, cb?: Callback<ChangeVote>): EventEmitter;

    Initialized(cb?: Callback<Initialized>): EventEmitter;
    Initialized(
      options?: EventOptions,
      cb?: Callback<Initialized>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    ProposalCanceled(cb?: Callback<ProposalCanceled>): EventEmitter;
    ProposalCanceled(
      options?: EventOptions,
      cb?: Callback<ProposalCanceled>
    ): EventEmitter;

    ProposalCreated(cb?: Callback<ProposalCreated>): EventEmitter;
    ProposalCreated(
      options?: EventOptions,
      cb?: Callback<ProposalCreated>
    ): EventEmitter;

    ProposalExecuted(cb?: Callback<ProposalExecuted>): EventEmitter;
    ProposalExecuted(
      options?: EventOptions,
      cb?: Callback<ProposalExecuted>
    ): EventEmitter;

    RemoveChangeableParameter(
      cb?: Callback<RemoveChangeableParameter>
    ): EventEmitter;
    RemoveChangeableParameter(
      options?: EventOptions,
      cb?: Callback<RemoveChangeableParameter>
    ): EventEmitter;

    SetChangeAbleParameters(
      cb?: Callback<SetChangeAbleParameters>
    ): EventEmitter;
    SetChangeAbleParameters(
      options?: EventOptions,
      cb?: Callback<SetChangeAbleParameters>
    ): EventEmitter;

    SetChangeableParameter(cb?: Callback<SetChangeableParameter>): EventEmitter;
    SetChangeableParameter(
      options?: EventOptions,
      cb?: Callback<SetChangeableParameter>
    ): EventEmitter;

    SetCreateProposalFee(cb?: Callback<SetCreateProposalFee>): EventEmitter;
    SetCreateProposalFee(
      options?: EventOptions,
      cb?: Callback<SetCreateProposalFee>
    ): EventEmitter;

    SetIsCoreContract(cb?: Callback<SetIsCoreContract>): EventEmitter;
    SetIsCoreContract(
      options?: EventOptions,
      cb?: Callback<SetIsCoreContract>
    ): EventEmitter;

    SubmitVote(cb?: Callback<SubmitVote>): EventEmitter;
    SubmitVote(options?: EventOptions, cb?: Callback<SubmitVote>): EventEmitter;

    SubmitVoteWithReason(cb?: Callback<SubmitVoteWithReason>): EventEmitter;
    SubmitVoteWithReason(
      options?: EventOptions,
      cb?: Callback<SubmitVoteWithReason>
    ): EventEmitter;

    SwitchDaoPhase(cb?: Callback<SwitchDaoPhase>): EventEmitter;
    SwitchDaoPhase(
      options?: EventOptions,
      cb?: Callback<SwitchDaoPhase>
    ): EventEmitter;

    VotingFinalized(cb?: Callback<VotingFinalized>): EventEmitter;
    VotingFinalized(
      options?: EventOptions,
      cb?: Callback<VotingFinalized>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "ChangeVote", cb: Callback<ChangeVote>): void;
  once(
    event: "ChangeVote",
    options: EventOptions,
    cb: Callback<ChangeVote>
  ): void;

  once(event: "Initialized", cb: Callback<Initialized>): void;
  once(
    event: "Initialized",
    options: EventOptions,
    cb: Callback<Initialized>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(event: "ProposalCanceled", cb: Callback<ProposalCanceled>): void;
  once(
    event: "ProposalCanceled",
    options: EventOptions,
    cb: Callback<ProposalCanceled>
  ): void;

  once(event: "ProposalCreated", cb: Callback<ProposalCreated>): void;
  once(
    event: "ProposalCreated",
    options: EventOptions,
    cb: Callback<ProposalCreated>
  ): void;

  once(event: "ProposalExecuted", cb: Callback<ProposalExecuted>): void;
  once(
    event: "ProposalExecuted",
    options: EventOptions,
    cb: Callback<ProposalExecuted>
  ): void;

  once(
    event: "RemoveChangeableParameter",
    cb: Callback<RemoveChangeableParameter>
  ): void;
  once(
    event: "RemoveChangeableParameter",
    options: EventOptions,
    cb: Callback<RemoveChangeableParameter>
  ): void;

  once(
    event: "SetChangeAbleParameters",
    cb: Callback<SetChangeAbleParameters>
  ): void;
  once(
    event: "SetChangeAbleParameters",
    options: EventOptions,
    cb: Callback<SetChangeAbleParameters>
  ): void;

  once(
    event: "SetChangeableParameter",
    cb: Callback<SetChangeableParameter>
  ): void;
  once(
    event: "SetChangeableParameter",
    options: EventOptions,
    cb: Callback<SetChangeableParameter>
  ): void;

  once(event: "SetCreateProposalFee", cb: Callback<SetCreateProposalFee>): void;
  once(
    event: "SetCreateProposalFee",
    options: EventOptions,
    cb: Callback<SetCreateProposalFee>
  ): void;

  once(event: "SetIsCoreContract", cb: Callback<SetIsCoreContract>): void;
  once(
    event: "SetIsCoreContract",
    options: EventOptions,
    cb: Callback<SetIsCoreContract>
  ): void;

  once(event: "SubmitVote", cb: Callback<SubmitVote>): void;
  once(
    event: "SubmitVote",
    options: EventOptions,
    cb: Callback<SubmitVote>
  ): void;

  once(event: "SubmitVoteWithReason", cb: Callback<SubmitVoteWithReason>): void;
  once(
    event: "SubmitVoteWithReason",
    options: EventOptions,
    cb: Callback<SubmitVoteWithReason>
  ): void;

  once(event: "SwitchDaoPhase", cb: Callback<SwitchDaoPhase>): void;
  once(
    event: "SwitchDaoPhase",
    options: EventOptions,
    cb: Callback<SwitchDaoPhase>
  ): void;

  once(event: "VotingFinalized", cb: Callback<VotingFinalized>): void;
  once(
    event: "VotingFinalized",
    options: EventOptions,
    cb: Callback<VotingFinalized>
  ): void;
}
