/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface IBonusScoreSystem extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IBonusScoreSystem;
  clone(): IBonusScoreSystem;
  methods: {
    getValidatorScore(mining: string): NonPayableTransactionObject<string>;

    penaliseBadPerformance(
      mining: string,
      time: number | string | BN
    ): NonPayableTransactionObject<void>;

    penaliseNoKeyWrite(mining: string): NonPayableTransactionObject<void>;

    penaliseNoStandBy(
      mining: string,
      time: number | string | BN
    ): NonPayableTransactionObject<void>;

    rewardStandBy(
      mining: string,
      time: number | string | BN
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
