/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface IDiamondDaoLowMajority extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IDiamondDaoLowMajority;
  clone(): IDiamondDaoLowMajority;
  methods: {
    execute(
      proposalId: number | string | BN,
      targets: string[],
      values: (number | string | BN)[],
      calldatas: (string | number[])[]
    ): NonPayableTransactionObject<void>;

    quorumReached(
      result: [
        number | string | BN,
        number | string | BN,
        number | string | BN,
        number | string | BN
      ],
      totalStakedAmount: number | string | BN
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
