/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Initialized = ContractEventLog<{
  version: string;
  0: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface KeyGenHistory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): KeyGenHistory;
  clone(): KeyGenHistory;
  methods: {
    acks(
      arg0: string,
      arg1: number | string | BN
    ): NonPayableTransactionObject<string>;

    clearPrevKeyGenState(
      _prevValidators: string[]
    ): NonPayableTransactionObject<void>;

    currentKeyGenRound(): NonPayableTransactionObject<string>;

    getAcksLength(val: string): NonPayableTransactionObject<string>;

    getCurrentKeyGenRound(): NonPayableTransactionObject<string>;

    getNumberOfKeyFragmentsWritten(): NonPayableTransactionObject<{
      0: string;
      1: string;
    }>;

    getPart(_val: string): NonPayableTransactionObject<string>;

    initialize(
      _contractOwner: string,
      _validatorSetContract: string,
      _validators: string[],
      _parts: (string | number[])[],
      _acks: (string | number[])[][]
    ): NonPayableTransactionObject<void>;

    notifyKeyGenFailed(): NonPayableTransactionObject<void>;

    notifyNewEpoch(): NonPayableTransactionObject<void>;

    numberOfAcksWritten(): NonPayableTransactionObject<string>;

    numberOfPartsWritten(): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    parts(arg0: string): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    validatorSet(
      arg0: number | string | BN
    ): NonPayableTransactionObject<string>;

    validatorSetContract(): NonPayableTransactionObject<string>;

    writeAcks(
      _upcommingEpoch: number | string | BN,
      _roundCounter: number | string | BN,
      _acks: (string | number[])[]
    ): NonPayableTransactionObject<void>;

    writePart(
      _upcommingEpoch: number | string | BN,
      _roundCounter: number | string | BN,
      _part: string | number[]
    ): NonPayableTransactionObject<void>;
  };
  events: {
    Initialized(cb?: Callback<Initialized>): EventEmitter;
    Initialized(
      options?: EventOptions,
      cb?: Callback<Initialized>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Initialized", cb: Callback<Initialized>): void;
  once(
    event: "Initialized",
    options: EventOptions,
    cb: Callback<Initialized>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
