/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface MockQuorumCalculator extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): MockQuorumCalculator;
  clone(): MockQuorumCalculator;
  methods: {
    highMajorityQuorum(
      vs: [
        number | string | BN,
        number | string | BN,
        number | string | BN,
        number | string | BN
      ],
      totalStakedAmount: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    lowMajorityQuorum(
      vs: [
        number | string | BN,
        number | string | BN,
        number | string | BN,
        number | string | BN
      ],
      totalStakedAmount: number | string | BN
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
