/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type NewOwner = ContractEventLog<{
  old: string;
  current: string;
  0: string;
  1: string;
}>;

export interface Owned extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Owned;
  clone(): Owned;
  methods: {
    owner(): NonPayableTransactionObject<string>;

    setOwner(_new: string): NonPayableTransactionObject<void>;
  };
  events: {
    NewOwner(cb?: Callback<NewOwner>): EventEmitter;
    NewOwner(options?: EventOptions, cb?: Callback<NewOwner>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "NewOwner", cb: Callback<NewOwner>): void;
  once(event: "NewOwner", options: EventOptions, cb: Callback<NewOwner>): void;
}
