/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ReentrancyAttacker extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ReentrancyAttacker;
  clone(): ReentrancyAttacker;
  methods: {
    attack(): NonPayableTransactionObject<void>;

    calls(): NonPayableTransactionObject<string>;

    dao(): NonPayableTransactionObject<string>;

    getBalance(): NonPayableTransactionObject<string>;

    proposalId(): NonPayableTransactionObject<string>;

    setId(_proposalId: number | string | BN): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
