/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ReentrancyAttacker extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ReentrancyAttacker;
  clone(): ReentrancyAttacker;
  methods: {
    attack(
      mining: string,
      time: number | string | BN
    ): NonPayableTransactionObject<void>;

    bonusScoreSystem(): NonPayableTransactionObject<string>;

    funcId(): NonPayableTransactionObject<string>;

    setBonusScoreContract(
      _bonusScoreSystem: string
    ): NonPayableTransactionObject<void>;

    setFuncId(id: string | number[]): NonPayableTransactionObject<void>;

    stakingFixedEpochDuration(): NonPayableTransactionObject<string>;

    timeArgValue(): NonPayableTransactionObject<string>;

    updatePoolLikelihood(
      mining: string,
      arg1: number | string | BN
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
